version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    container_name: frontend

  backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    container_name: backend
    environment:
      - PORT=3001

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend